### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Didel** [LibreScore/LibreScore#4]
On NodeJS 14 (on MacOS), I am unable to run `npm install` for LibreScore.

```
../src/secp256k1/src/scalar_4x64_impl.h:969:5: error: implicitly declaring library function
      'memcpy' with type 'void *(void *, const void *, unsigned long)'
      [-Werror,-Wimplicit-function-declaration]
    memcpy((void *) seed32, (const void *) seed, 32);
    ^
../src/secp256k1/src/scalar_4x64_impl.h:969:5: note: include the header <string.h> or
      explicitly provide a declaration for 'memcpy'
1 error generated.
make: *** [Release/obj.target/bcrypto/src/secp256k1/src/secp256k1.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
```

**Comment by PeterNjeim** [comment]
Not reproducible in latest build
